name: Publish Python Package to TestPyPI

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          pip install numpy opencv-python scipy
          
      - name: Auto-increment Version
        run: |
          awk -F' '/version=/ {print $2}' setup.py > old_version.txt
          OLD_VERSION=$(cat old_version.txt)
          NEW_VERSION=$(echo $OLD_VERSION | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          sed -i "s/version='$OLD_VERSION'/version='$NEW_VERSION'/" setup.py
          echo "New version: $NEW_VERSION"
      
      - name: Build Package
        run: python -m build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: pypi-AgENdGVzdC5weXBpLm9yZwIkZDFjZmE4YzctMmEwNi00MjhlLWE0ODktZDhiNTEwZDc1ZTc4AAIqWzMsImJjZmUzNWFjLTExN2MtNGRiYS05YTljLWY3YzAwYjRkN2EzZSJdAAAGIHDXU-oVXV48ia9ScMwDaUp3VfvT8-J-Yxl6V7NGLvtp
        run: twine upload --repository testpypi dist/*
